services:
  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile          # ← your multi-stage Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/ssl/djgrego.com:/etc/ssl/djgrego.com:ro
    depends_on:
      - backend
    networks:
      - app-network
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - CORS_ORIGINS=https://djgrego.com
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  frontend-build: