version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl/djgrego.com/djgrego.com.pem:/etc/nginx/certs/djgrego.com.pem:ro
      - /etc/ssl/djgrego.com/djgrego.com.key:/etc/nginx/certs/djgrego.com.key:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "8000"
    environment:
      - CORS_ORIGINS=https://djgrego.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge