version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./djgrego.com.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    expose:
      - "8000"
    environment:
      - CORS_ORIGINS=https://djgrego.com
    networks:
      - app-network

networks:
  app-network:
    driver: bridge