services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    environment:
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: unless-stopped